import type { Metadata } from 'next';
import Link from 'next/link';
import Header from '@/components/layout/Header';

export const metadata: Metadata = {
  title: 'Privacy Policy | CV Builder',
  description: 'Privacy Policy for CV Builder — how we collect, use, and protect your data.',
  robots: { index: false },
};

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-slate-50">
      <Header />
      <main className="max-w-3xl mx-auto px-4 py-12">

        {/* Breadcrumb */}
        <nav className="mb-8 text-sm text-slate-500">
          <Link href="/" className="hover:text-slate-700 transition">Home</Link>
          <span className="mx-2">/</span>
          <span className="text-slate-700">Privacy Policy</span>
        </nav>

        <h1 className="text-4xl font-bold text-slate-900 mb-2">Privacy Policy</h1>
        <p className="text-slate-500 mb-8">Effective date: February 2026</p>

        <p className="text-slate-700 leading-relaxed mb-6">
          CV Builder is committed to protecting your privacy. This Privacy Policy explains what
          data we collect, how we use it, and your rights under the UK General Data Protection
          Regulation (UK GDPR) and the Data Protection Act 2018.
        </p>

        {/* 1. Data Controller */}
        <h2 className="text-2xl font-bold text-slate-900 mb-4 mt-8">1. Data Controller</h2>
        <p className="text-slate-700 leading-relaxed mb-4">
          The data controller for your personal information is CV Builder. For any data-related
          enquiries, please contact us at:{' '}
          <a href="mailto:privacy@cvbuilder.co.uk" className="text-blue-600 hover:underline">
            privacy@cvbuilder.co.uk
          </a>
        </p>

        {/* 2. What Data We Collect */}
        <h2 className="text-2xl font-bold text-slate-900 mb-4 mt-8">2. What Data We Collect</h2>

        <h3 className="text-lg font-semibold text-slate-800 mb-2 mt-6">Guest users (no account)</h3>
        <p className="text-slate-700 leading-relaxed mb-4">
          When you use CV Builder without an account, your CV content is stored only in your
          browser's LocalStorage. We do not collect or store your CV content on our servers.
          We do not collect any personally identifiable information from guest users during
          normal use.
        </p>
        <p className="text-slate-700 leading-relaxed mb-4">
          When you export a PDF as a guest, your CV data is temporarily transmitted to our
          PDF rendering service (Cloudflare Workers) to generate the document. This data is
          not retained after your PDF is delivered.
        </p>

        <h3 className="text-lg font-semibold text-slate-800 mb-2 mt-6">Registered users (with account)</h3>
        <p className="text-slate-700 leading-relaxed mb-4">When you create an account, we collect and store:</p>
        <ul className="list-disc list-inside text-slate-700 leading-relaxed mb-4 space-y-1">
          <li>Your email address (used for authentication)</li>
          <li>A unique user identifier (UUID, generated by Supabase)</li>
          <li>Your CV content (stored securely in our database)</li>
          <li>Export history (template used, timestamps)</li>
        </ul>

        <h3 className="text-lg font-semibold text-slate-800 mb-2 mt-6">Purchases (Export Pass)</h3>
        <p className="text-slate-700 leading-relaxed mb-4">
          When you purchase an Export Pass, we collect:
        </p>
        <ul className="list-disc list-inside text-slate-700 leading-relaxed mb-4 space-y-1">
          <li>Your email address (to associate the purchase)</li>
          <li>Purchase status, timestamps, and Stripe session identifiers</li>
        </ul>
        <p className="text-slate-700 leading-relaxed mb-4">
          We do not store your card number, CVV, or full payment details. All payment processing
          is handled directly by Stripe. Please review{' '}
          <a
            href="https://stripe.com/gb/privacy"
            target="_blank"
            rel="noopener noreferrer"
            className="text-blue-600 hover:underline"
          >
            Stripe's Privacy Policy
          </a>{' '}
          for details of how Stripe handles your payment data.
        </p>

        <h3 className="text-lg font-semibold text-slate-800 mb-2 mt-6">Analytics</h3>
        <p className="text-slate-700 leading-relaxed mb-4">
          We use Plausible Analytics, a privacy-friendly analytics tool. Plausible does not use
          cookies and does not collect personal data. It records only anonymous, aggregate statistics
          (such as page views and general geographic region) to help us understand how the service
          is used. No individual user is tracked or profiled.
        </p>

        <h3 className="text-lg font-semibold text-slate-800 mb-2 mt-6">Server logs</h3>
        <p className="text-slate-700 leading-relaxed mb-4">
          Our hosting providers (Vercel and Cloudflare) automatically record server logs including
          IP addresses and request metadata. These logs are used solely for security monitoring
          and are retained for a short period in accordance with each provider's policies. We do
          not actively process these logs for business purposes.
        </p>

        {/* 3. Legal Basis */}
        <h2 className="text-2xl font-bold text-slate-900 mb-4 mt-8">3. Legal Basis for Processing</h2>
        <ul className="list-disc list-inside text-slate-700 leading-relaxed mb-4 space-y-2">
          <li>
            <strong>Contract performance:</strong> Processing your account data and purchase
            records is necessary to provide the service you have requested.
          </li>
          <li>
            <strong>Legitimate interests:</strong> Anonymous analytics and server log retention
            serve our legitimate interest in maintaining and improving the service.
          </li>
          <li>
            <strong>Legal obligation:</strong> We retain purchase records for the minimum period
            required by UK accounting and tax law.
          </li>
        </ul>

        {/* 4. How We Use Your Data */}
        <h2 className="text-2xl font-bold text-slate-900 mb-4 mt-8">4. How We Use Your Data</h2>
        <ul className="list-disc list-inside text-slate-700 leading-relaxed mb-4 space-y-1">
          <li>To provide, operate, and improve the CV Builder service</li>
          <li>To render and deliver your PDF exports</li>
          <li>To authenticate your account and maintain your session</li>
          <li>To process payments and verify Export Pass entitlement</li>
          <li>To respond to support requests and account queries</li>
          <li>To understand aggregate usage patterns and improve the service (anonymous analytics only)</li>
        </ul>
        <p className="text-slate-700 leading-relaxed mb-4">
          We do not sell your personal data to any third party.
        </p>

        {/* 5. Data Retention */}
        <h2 className="text-2xl font-bold text-slate-900 mb-4 mt-8">5. Data Retention</h2>
        <ul className="list-disc list-inside text-slate-700 leading-relaxed mb-4 space-y-2">
          <li>
            <strong>CV content and export history:</strong> Retained until you delete your account.
          </li>
          <li>
            <strong>Purchase records:</strong> Retained for 7 years in accordance with UK
            accounting and HMRC requirements, even after account deletion. Where possible,
            purchase records are anonymised on account deletion.
          </li>
          <li>
            <strong>Analytics data:</strong> Aggregate-only; automatically deleted after 12 months.
          </li>
          <li>
            <strong>PDF exports in storage:</strong> Retained for up to 90 days from generation,
            after which they are automatically deleted.
          </li>
        </ul>

        {/* 6. Your Rights */}
        <h2 className="text-2xl font-bold text-slate-900 mb-4 mt-8">6. Your Rights</h2>
        <p className="text-slate-700 leading-relaxed mb-4">
          Under UK GDPR, you have the following rights:
        </p>
        <ul className="list-disc list-inside text-slate-700 leading-relaxed mb-4 space-y-2">
          <li>
            <strong>Right of access:</strong> You may request a copy of the personal data we hold
            about you.
          </li>
          <li>
            <strong>Right to rectification:</strong> You may correct inaccurate data via your
            account settings.
          </li>
          <li>
            <strong>Right to erasure:</strong> You may delete your account and all associated CV
            data at any time via your account settings.
          </li>
          <li>
            <strong>Right to data portability:</strong> You may export your CV data as a JSON file
            from your account settings.
          </li>
          <li>
            <strong>Right to object:</strong> You may object to processing based on legitimate
            interests. For analytics, Plausible records only anonymous data so there is no
            individual profile to opt out of.
          </li>
        </ul>
        <p className="text-slate-700 leading-relaxed mb-4">
          To exercise your rights, contact us at{' '}
          <a href="mailto:privacy@cvbuilder.co.uk" className="text-blue-600 hover:underline">
            privacy@cvbuilder.co.uk
          </a>
          . We will respond within 30 days in accordance with UK GDPR requirements.
        </p>
        <p className="text-slate-700 leading-relaxed mb-4">
          You also have the right to lodge a complaint with the UK Information Commissioner's
          Office (ICO) at{' '}
          <a
            href="https://ico.org.uk"
            target="_blank"
            rel="noopener noreferrer"
            className="text-blue-600 hover:underline"
          >
            ico.org.uk
          </a>
          .
        </p>

        {/* 7. Data Security */}
        <h2 className="text-2xl font-bold text-slate-900 mb-4 mt-8">7. Data Security</h2>
        <p className="text-slate-700 leading-relaxed mb-4">
          We implement appropriate technical and organisational measures to protect your data:
        </p>
        <ul className="list-disc list-inside text-slate-700 leading-relaxed mb-4 space-y-1">
          <li>All data is transmitted over HTTPS (encrypted in transit)</li>
          <li>Data at rest is encrypted by Supabase</li>
          <li>Database access is protected by Row-Level Security (RLS) policies, ensuring users can only access their own data</li>
          <li>Signed URLs with short expiry periods are used for stored PDF files</li>
        </ul>

        {/* 8. Sub-Processors */}
        <h2 className="text-2xl font-bold text-slate-900 mb-4 mt-8">8. Sub-Processors</h2>
        <p className="text-slate-700 leading-relaxed mb-4">
          We use the following third-party services to operate CV Builder. Each sub-processor
          has been assessed for GDPR compliance:
        </p>
        <div className="overflow-x-auto mb-6">
          <table className="w-full text-sm text-slate-700 border border-slate-200 rounded-lg">
            <thead className="bg-slate-100">
              <tr>
                <th className="text-left px-4 py-3 font-semibold">Provider</th>
                <th className="text-left px-4 py-3 font-semibold">Purpose</th>
                <th className="text-left px-4 py-3 font-semibold">Location</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-200">
              <tr>
                <td className="px-4 py-3 font-medium">Supabase</td>
                <td className="px-4 py-3">Database, authentication, file storage</td>
                <td className="px-4 py-3">EU (Ireland) / US</td>
              </tr>
              <tr>
                <td className="px-4 py-3 font-medium">Vercel</td>
                <td className="px-4 py-3">Application hosting and server-side rendering</td>
                <td className="px-4 py-3">Global (EU / US)</td>
              </tr>
              <tr>
                <td className="px-4 py-3 font-medium">Cloudflare</td>
                <td className="px-4 py-3">PDF rendering service, CDN</td>
                <td className="px-4 py-3">Global</td>
              </tr>
              <tr>
                <td className="px-4 py-3 font-medium">Stripe</td>
                <td className="px-4 py-3">Payment processing</td>
                <td className="px-4 py-3">EU / US</td>
              </tr>
              <tr>
                <td className="px-4 py-3 font-medium">Plausible Analytics</td>
                <td className="px-4 py-3">Anonymous usage analytics (no cookies, no PII)</td>
                <td className="px-4 py-3">EU (Germany)</td>
              </tr>
              <tr>
                <td className="px-4 py-3 font-medium">Sentry</td>
                <td className="px-4 py-3">Error monitoring (no CV content logged)</td>
                <td className="px-4 py-3">US</td>
              </tr>
            </tbody>
          </table>
        </div>

        {/* 9. International Transfers */}
        <h2 className="text-2xl font-bold text-slate-900 mb-4 mt-8">9. International Data Transfers</h2>
        <p className="text-slate-700 leading-relaxed mb-4">
          Some of our sub-processors operate outside the UK or European Economic Area (EEA),
          including in the United States. Where data is transferred internationally, we rely on
          appropriate safeguards such as Standard Contractual Clauses (SCCs) or the UK
          International Data Transfer Agreement (IDTA) to ensure an equivalent level of
          protection.
        </p>

        {/* 10. Children */}
        <h2 className="text-2xl font-bold text-slate-900 mb-4 mt-8">10. Children's Privacy</h2>
        <p className="text-slate-700 leading-relaxed mb-4">
          CV Builder is not intended for use by individuals under the age of 16. We do not
          knowingly collect personal data from children. If you believe we have inadvertently
          collected data from a child, please contact us and we will delete it promptly.
        </p>

        {/* 11. Cookies */}
        <h2 className="text-2xl font-bold text-slate-900 mb-4 mt-8">11. Cookies</h2>
        <p className="text-slate-700 leading-relaxed mb-4">
          For full details of how we use cookies and browser storage, please see our{' '}
          <Link href="/cookies" className="text-blue-600 hover:underline">Cookie Policy</Link>.
          In summary, we use only essential session cookies for login and do not use advertising
          or tracking cookies.
        </p>

        {/* 12. Changes */}
        <h2 className="text-2xl font-bold text-slate-900 mb-4 mt-8">12. Changes to This Policy</h2>
        <p className="text-slate-700 leading-relaxed mb-4">
          We may update this Privacy Policy from time to time. We will notify registered users
          of material changes via email or an in-app notice. We encourage you to review this
          page periodically. The effective date at the top indicates when this policy was last
          revised.
        </p>

        {/* 13. Contact */}
        <h2 className="text-2xl font-bold text-slate-900 mb-4 mt-8">13. Contact</h2>
        <p className="text-slate-700 leading-relaxed mb-4">
          For privacy-related questions, data access requests, or complaints, please contact:
        </p>
        <address className="not-italic text-slate-700 leading-relaxed mb-4">
          CV Builder<br />
          Email:{' '}
          <a href="mailto:privacy@cvbuilder.co.uk" className="text-blue-600 hover:underline">
            privacy@cvbuilder.co.uk
          </a>
        </address>

        <hr className="border-slate-200 mt-12 mb-6" />
        <p className="text-sm text-slate-400">Last updated: February 2026</p>
      </main>
    </div>
  );
}
